import { ModeToggle } from '@/components/ModeToggle'
import Nav from '@/components/Nav'
import { ThemeProvider } from '@/components/ThemeProvider'
import { TooltipProvider } from '@/components/ui/tooltip'
import '@/global.css'
import '@fontsource/roboto'
import React from 'react'
import { Toaster } from 'sonner'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-background text-primary w-screen h-screen">
        <Toaster richColors closeButton></Toaster>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <div className="h-[50px] flex justify-end items-center space-x-2 px-2">
              <Nav></Nav>
              <ModeToggle></ModeToggle>
            </div>
            <div className="w-full h-[calc(100vh-50px)]">{children}</div>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
